# Generated by Django 4.0 on 2023-10-26 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('tg_account', models.CharField(max_length=20, verbose_name='Телеграм-аккаунт')),
                ('trello_account', models.CharField(max_length=20, verbose_name='Трелло-аккаунт')),
                ('chat_id', models.IntegerField(blank=True, null=True, verbose_name='ChatID пользователя')),
            ],
            options={
                'verbose_name': 'Проект-менеджер',
                'verbose_name_plural': 'Проект-менеджеры',
            },
        ),
        migrations.CreateModel(
            name='TeamWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(db_index=True, default=datetime.time(19, 0), verbose_name='Начало диапазона')),
                ('end_time', models.TimeField(db_index=True, default=datetime.time(19, 20), verbose_name='Конец диапазона')),
                ('project_manager', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='teamwork', to='devman.projectmanager', verbose_name='Проект-менеджер')),
            ],
            options={
                'verbose_name': 'Проект-менеджер',
                'verbose_name_plural': 'Проект-менеджеры',
                'unique_together': {('project_manager', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('level', models.CharField(choices=[('june', 'june'), ('newbie+', 'newbie+'), ('newbie', 'newbie')], default='newbie', max_length=10, verbose_name='Уровень')),
                ('tg_account', models.CharField(max_length=20, verbose_name='Телеграм-аккаунт')),
                ('trello_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Трелло-аккаунт')),
                ('far_east', models.BooleanField(default=False, verbose_name='С Дальнего Востока')),
                ('start_time', models.TimeField(db_index=True, default=datetime.time(8, 0), verbose_name='Начало диапазона')),
                ('end_time', models.TimeField(db_index=True, default=datetime.time(20, 0), verbose_name='Конец диапазона')),
                ('chat_id', models.IntegerField(blank=True, null=True, verbose_name='ChatID пользователя')),
                ('teamwork', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='teamwork', to='devman.teamwork', verbose_name='Группа проекта')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Cтуденты',
            },
        ),
    ]
