# Generated by Django 4.0 on 2023-10-25 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('tg_account', models.CharField(max_length=20, verbose_name='Телеграм-аккаунт')),
                ('trello_account', models.CharField(max_length=20, verbose_name='Трелло-аккаунт')),
            ],
            options={
                'verbose_name': 'Проект-менеджер',
                'verbose_name_plural': 'Проект-менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('level', models.CharField(choices=[('June', 'June'), ('newbie+', 'newbie+'), ('newbie', 'newbie')], default='newbie', max_length=10, verbose_name='Уровень')),
                ('tg_account', models.CharField(max_length=20, verbose_name='Телеграм-аккаунт')),
                ('trello_account', models.CharField(max_length=20, verbose_name='Трелло-аккаунт')),
                ('far_east', models.BooleanField(default=False, verbose_name='С Дальнего Востока')),
                ('start_time', models.TimeField(db_index=True, default=datetime.time(8, 0), verbose_name='Начало диапазона')),
                ('end_time', models.TimeField(db_index=True, default=datetime.time(20, 0), verbose_name='Конец диапазона')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Cтуденты',
            },
        ),
    ]
