# Generated by Django 4.0 on 2023-10-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamwork',
            options={'verbose_name': 'Группа проекта', 'verbose_name_plural': 'Группы проекта'},
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='trello_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TrelloID пользователя'),
        ),
        migrations.AddField(
            model_name='student',
            name='trello_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='TrelloID пользователя'),
        ),
        migrations.AddField(
            model_name='teamwork',
            name='trello_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на доску в Trello'),
        ),
    ]
