# Generated by Django 4.0 on 2023-10-23 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(db_index=True, default=datetime.time(8, 0), verbose_name='Начало диапазона')),
                ('end_time', models.TimeField(db_index=True, default=datetime.time(20, 0), verbose_name='Начало диапазона')),
            ],
            options={
                'verbose_name': 'Временной диапазон',
                'verbose_name_plural': 'Временные диапазоны',
            },
        ),
    ]
