# Generated by Django 4.0 on 2023-10-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0002_alter_teamwork_options_projectmanager_trello_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='trello_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='TrelloID пользователя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teamwork',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='student', to='devman.teamwork', verbose_name='Группа проекта'),
        ),
    ]
