# Generated by Django 4.0 on 2023-10-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0002_alter_student_teamwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamwork',
            name='project_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='teamworks', to='devman.projectmanager', verbose_name='Проект-менеджер'),
        ),
    ]
