# Generated by Django 4.0 on 2023-10-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0002_alter_student_trello_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('june', 'june'), ('newbie+', 'newbie+'), ('newbie', 'newbie')], default='newbie', max_length=10, verbose_name='Уровень'),
        ),
    ]
