# Generated by Django 4.0 on 2023-10-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0003_student_time_range_alter_time_range_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_range',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students', to='devman.time_range'),
        ),
    ]
