# Generated by Django 4.0 on 2023-10-29 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0003_alter_teamwork_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWorkCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(db_index=True, default=datetime.time(19, 0), verbose_name='Начало созвона')),
                ('end_time', models.TimeField(db_index=True, default=datetime.time(19, 20), verbose_name='Окончание созвона')),
                ('project_manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='сalculation_teamworks', to='devman.projectmanager', verbose_name='Проект-менеджер')),
            ],
            options={
                'verbose_name': 'Группа для расчетов',
                'verbose_name_plural': 'Группы для расчетов',
                'unique_together': {('project_manager', 'start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='calculation_teamwork',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='students_candidate', to='devman.TeamWorkCalculation', verbose_name='Группа кандидатов'),
        ),
    ]
