# Generated by Django 4.0 on 2023-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0003_alter_projectmanager_trello_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamwork',
            name='discord_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка приглашение на дискорд сервер'),
        ),
    ]
