# Generated by Django 4.0 on 2023-10-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0004_teamwork_discord_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='trello_key',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='TrelloID пользователя'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='trello_token',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='TrelloID пользователя'),
        ),
    ]
