# Generated by Django 4.0 on 2023-10-30 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0004_teamworkcalculation_student_calculation_teamwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='end_time',
            field=models.TimeField(db_index=True, default=datetime.time(20, 0), verbose_name='Конец диапазона'),
        ),
    ]
