# Generated by Django 4.0 on 2023-10-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0004_alter_student_time_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_range',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students', to='devman.time_range'),
        ),
    ]
