# Generated by Django 4.0 on 2023-10-27 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0005_projectmanager_trello_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamwork',
            name='end_time',
            field=models.TimeField(db_index=True, default=datetime.time(19, 20), verbose_name='Окончание созвона'),
        ),
        migrations.AlterField(
            model_name='teamwork',
            name='start_time',
            field=models.TimeField(db_index=True, default=datetime.time(19, 0), verbose_name='Начало созвона'),
        ),
    ]
