# Generated by Django 4.0 on 2023-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0005_alter_student_time_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='far_east',
            field=models.BooleanField(default=False, verbose_name='С Дальнего Востока'),
        ),
    ]
