# Generated by Django 4.0 on 2023-10-24 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0006_student_far_east'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='time_range',
        ),
        migrations.AddField(
            model_name='student',
            name='end_time',
            field=models.TimeField(db_index=True, default=datetime.time(20, 0), verbose_name='Конец диапазона'),
        ),
        migrations.AddField(
            model_name='student',
            name='start_time',
            field=models.TimeField(db_index=True, default=datetime.time(8, 0), verbose_name='Начало диапазона'),
        ),
        migrations.DeleteModel(
            name='Time_range',
        ),
    ]
