# Generated by Django 4.0 on 2023-10-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0006_alter_teamwork_end_time_alter_teamwork_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='trello_key',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Trello-key'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='trello_token',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Trello-token'),
        ),
    ]
