# Generated by Django 4.0 on 2023-10-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0007_remove_student_time_range_student_end_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_manager',
            new_name='ProjectManager',
        ),
    ]
